### ISSUE TITLE
Offer build which runs on latest stable Ubuntu

### ISSUE THREAD

**Issue by PanderMusubi** [gobytecoin/gobyte#11]
The current build v0.12.1.3 does not run on the current version of Ubuntu, which is 17.10. The problem is the version of libboost. Gobyte was build with libboost version 1.58, while Ubuntu ships with version 1.62. Please fix this so that users can run the wallet on latest stable Ubuntu.

Also, version 18.04 of Ubuntu, which is coming up in April, will ship with libboost version 1.65. So please also offer a bulid for that version.

I know there are tricks to build all this yourself on Ubuntu, but that is for most users way too difficult or cumbersome. Offering these build will increase the user base and improve the image for this wallet.

**Comment by PanderMusubi** [comment]
There has been a commit related to this https://github.com/gobytecoin/gobyte/commit/35d1579126dd09b32daac97f8cd78af9e337de50 Hope to see new libboost support in a next release.

**Comment by marknl** [comment]
Fixed in 0.12.3
