### ISSUE TITLE
libtool for -rpath problems

### ISSUE THREAD

**Issue by 26rahulsingh** [gobytecoin/gobyte#12]
./autogen.sh
---------------- 
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:52: installing 'build-aux/compile'
configure.ac:25: installing 'build-aux/missing'
Makefile.am:5: warning: user variable 'GZIP_ENV' defined here ...
/usr/share/automake-1.15/am/distdir.am: ... overrides Automake variable 'GZIP_ENV' defined here
Makefile.am:58: warning: user target 'distcleancheck' defined here ...
/usr/share/automake-1.15/am/distdir.am: ... overrides Automake target 'distcleancheck' defined here
src/Makefile.am: installing 'build-aux/depcomp'
src/Makefile.am:516: warning: user target '.mm.o' defined here ...
/usr/share/automake-1.15/am/depend2.am: ... overrides Automake target '.mm.o' defined here

./configure
--------------
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating pc/libunivalue.pc
config.status: creating pc/libunivalue-uninstalled.pc
config.status: creating univalue-config.h
config.status: univalue-config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
Fixing libtool for -rpath problems.

make
-------
Making all in src
make[1]: Entering directory '/home/devjs/gobyte/gobyte/src'
make[2]: Entering directory '/home/devjs/gobyte/gobyte/src'
  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX      crypto/libbitcoinconsensus_la-sha1.lo
  CXX      crypto/libbitcoinconsensus_la-sha256.lo
  CXX      crypto/libbitcoinconsensus_la-sha512.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      script/libbitcoinconsensus_la-bitcoinconsensus.lo
  CXX      script/libbitcoinconsensus_la-interpreter.lo
  CXX      script/libbitcoinconsensus_la-script.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
make[3]: Entering directory '/home/devjs/gobyte/gobyte/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Leaving directory '/home/devjs/gobyte/gobyte/src/secp256k1'
  CXXLD    libbitcoinconsensus.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: *** No rule to make target 'gobyted.cpp', needed by 'gobyted-gobyted.o'.  Stop.
make[2]: Leaving directory '/home/devjs/gobyte/gobyte/src'
Makefile:9080: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/devjs/gobyte/gobyte/src'
Makefile:652: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

i'm using ubuntu 16.04 and also tried with Debian 9.3 getting same error.

**Comment by insaneITgeek** [comment]
AnyUpdate on this error? Because i have same error

**Comment by marknl** [comment]
Always compile using "depends" folder.

cd into gobyte folder, then:
```bash
cd depends
make -j2
cd ..
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu
make```
