### ISSUE TITLE
Masternode status "WATCHDOG_EXPIRED"  ?? 

### ISSUE THREAD

**Issue by AH1111** [gobytecoin/gobyte#17]
I updated my wallet this am.
The masternode status is "Watchdog Expired"  What do I do to get back to enabled status?

**Comment by D0WN3D** [comment]
Install the sentinel from here.
https://github.com/gobytecoin/sentinel

**Comment by Shekelme** [comment]
What if sentinel has been installed from the beginning of MN deployment? That is my case, but I found that MN is in "New start required" state, but after I did "Start alias" - the status has changed to "Watchdog expired".

**Comment by Shekelme** [comment]
OK, I have Sentinell installed, and everything has been configured well and my MN was working OK. But now I see a "WATCHDOG_EXPIRED_ message whatever I do. Please help me to make a MN work as intended again.

**Comment by marknl** [comment]
You get WATCHDOG_EXPIRED if sentinel is not working properly. So you know where to look now, sentinel. Run it manually, and it should give an error on screen.

**Comment by marknl** [comment]
@Shekelme Don't post comments in closed issues, since you've already made a new issue. Thank you.
