### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by egyptianbman** [gobytecoin/gobyte#25]
We run a shared masternode service, hosting for many various coins. One of the coins we host is gobyte which consistently uses around 150-165% cpu (of one core).  I'm not sure what the cause is of the high cpu usage, it seems there may be some inefficiencies in the masternode code.

**Comment by GoByteDev** [comment]
Hi @egyptianbman 

You can reduce the load by add this value on gobyte.conf

> maxconnections=12

**Comment by egyptianbman** [comment]
That did the trick, thank you!
