### ISSUE TITLE
Problem with libboost_system.so.1.58.0 (Ubuntu 18.04.4)

### ISSUE THREAD

**Issue by Shekelme** [gobytecoin/gobyte#32]
Ubuntu 18.04.4. Once I found that gobyted can't be started anymore. Because of

`./gobyted: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory`

So after I created a bunch of symbolic links to many of newer libraries as the problems were appearing, finally I've got this error:

`./gobyted: symbol lookup error: ./gobyted: undefined symbol: _ZN5boost11this_thread5hiden9sleep_forERK8timespec
`

**Comment by marknl** [comment]
Use launchpad: https://launchpad.net/~gobytecoin/+archive/ubuntu/gobyte
