### ISSUE TITLE
cannot run Linux wallet, missing libraries

### ISSUE THREAD

**Issue by FlorinAndrei** [gobytecoin/gobyte#4]
Your Linux binary appears to depend on a very specific Linux version, and it will not run elsewhere.

I'm trying to run your Linux wallet on Ubuntu 16.04. First it gave me this error:

```
./gobyte-qt: error while loading shared libraries: libqrencode.so.3: cannot open shared object file: No such file or directory
```

I was able to fix it by installing `libqrencode3`.

Then it produced this error:

```
./gobyte-qt: error while loading shared libraries: libdb_cxx-4.8.so: cannot open shared object file: No such file or directory
```

I could not fix it. Ubuntu 16.04 does not appear to include that library.

It would be great if you could do static linking on your Linux binaries. This way they will not depend on specific libraries being installed on the system - as long as the kernel is not extremely old they will run just fine on any distribution.

Also, currently your statement that you're providing a "Linux wallet" is a bit misleading. You're providing a wallet that only runs on a specific Linux distribution.

**Comment by Himan2001** [comment]
use the depends-folder and include them to the configure command. take a look into the doc folder how to to this. Or download libdb4.8.NC from bitcoin ppa. When you build by just using the configure command (without the depends folder) the resulting binarys are use only shared libs and depends on your actual linux system and libs versions. So best is to use depends folder to get an nearly entire static binary.

**Comment by FlorinAndrei** [comment]
@Himan2001 I'll give it a try when I get a chance. But if what you're saying is correct, then that should be made the default compile option.

**Comment by Himan2001** [comment]
by using the "depends" folder and include it in a self-made "configure.sh" script - you compile always static as possible :-)

**Comment by D0WN3D** [comment]
> Also, currently your statement that you're providing a "Linux wallet" is a bit misleading. You're providing a wallet that only runs on a specific Linux distribution.

How comes you're the only one with this problem, ehm?

**Comment by piraz** [comment]
I had the same problem. Compiled from the source in Fedora 27.

**Comment by michiel1972** [comment]
Linux wallet does not work on Sonya Mint (Ubuntu 16.04):

error while loading shared libraries: libboost_program_options.so.1.58.0

**Comment by marknl** [comment]
Always compile using "depends" folder.

cd into gobyte folder, then:
```bash
cd depends
make -j2
cd ..
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu
make
```
