### ISSUE TITLE
depends folder outdated and resulted segfaults on ubuntu 16.04

### ISSUE THREAD

**Issue by Himan2001** [gobytecoin/gobyte#5]
Using the depends folder from the master results in segfaulted binarys on ubuntu 16.04.
compiling directly with the systemlibs works. (but all is shared then...)

After short checking the used versions in depends folder i will suggest to update the version numbers and patches, especialy openssl, zmq, boost and qt to a more actual version.

Further more the libsodium package is missing and needs to be added. version 14 or 15 is an open question. by using a never qt5-version the package zlib needs to be added. A good base is the depends folder from latest bitcoin-core or btcgold.

**Comment by Himan2001** [comment]
I figured out the reason for the segfaults with actual and newer libs:
i changed -O2 ro -O3 at the depends makefile - and this is no longer working with actual bitcoin cores!
Changing it back to -O2 fixed the segfaults - but code is then less optimized for the native system...

**Comment by PanderMusubi** [comment]
See also https://github.com/gobytecoin/gobyte/issues/11

**Comment by marknl** [comment]
depends folder up to date as of version v0.12.3 (will be released soon)
