### ISSUE TITLE
how do i run the linux wallet

### ISSUE THREAD

**Issue by eliddell1** [gobytecoin/gobyte#7]
i cloned the repo. ran ./autogen.sh , ./configure and make now what?

**Comment by dennisclausen** [comment]
i downloaded the precompiled version and it gives me the following:

./gobyted: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory

**Comment by Eneen** [comment]
Where have you got precompiled binary from?

**Comment by Alwinius** [comment]
https://github.com/gobytecoin/gobyte/releases Here are the releases. This should definitely be linked to somewhere. But I get a similar error like dennisclausen. It's 
`./gobyted: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory`
This is the same for all binaries.

**Comment by cajdavidson** [comment]
@Alwinius I needed to install the following dependencies on Ubuntu 16.04 to get the wallet up and running... (note that some of these may not be required, but they got it up and running for me).

add-apt-repository -y ppa:bitcoin/bitcoin
apt-get install build-essential libssl-dev libboost-all-dev libqrencode-dev libminiupnpc-dev libboost-system1.58.0 libboost1.58-all-dev libdb4.8++ libdb4.8 libdb4.8-dev libdb4.8++-dev libevent-pthreads-2.0-5

**Comment by PanderMusubi** [comment]
See also https://github.com/gobytecoin/gobyte/issues/11
