### ISSUE TITLE
Solo mining?

### ISSUE THREAD

**Issue by milewski** [gobytecoin/gobyte#9]
how do i solo mine this coin? any tips? stratum package available? on click docker file?

**Comment by Himan2001** [comment]
For the moment solo works only with the (slow) "nanashi-solo-mining 2.2x" version.
I use a "fix" and installed "yiimp-next" on a local vserver and use the latest KlausT-ccminer to mine
on private pool....

**Comment by milewski** [comment]
well at this point in time this coin already dead... not worth anymore
